name: frame

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  connectivity_plus: ^7.3.1
  internet_connection_checker_plus: ^3.1.1
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  webview_flutter: ^4.13.0
  youtube_player_iframe: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - images/

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "images/Gemini_Generated_Image_t9f0gst9f0gst9f0.png"

  web:
    generate: true
    image_path: "images/Gemini_Generated_Image_t9f0gst9f0gst9f0.png"
    background_color: "#00000000"
    theme_color: "#00000000"

  windows:
    generate: true
    image_path: "images/Gemini_Generated_Image_t9f0gst9f0gst9f0.png"

  macos:
    generate: true
    image_path: "images/Gemini_Generated_Image_t9f0gst9f0gst9f0.png"